Algoritmo ejemplo1
	// ESTRUCTURA SELECTIVA - IF
	// IF DEVUELVE VERDADERO O FALSO
	// OPERADORES RELACIONALES
	Leer NUM
	Si NUM>0 Entonces
		Escribir "Es positivo"
		// OBLIGATORIO HAYA INSTRUCCIONES
	SiNo
		// OPTATIVA
	FinSi
FinAlgoritmo
